### ISSUE TITLE
US05 - Cadastrar Módulos

### ISSUE THREAD

**Issue by vinicinolivera** [zero101010/PI1_2018_2#19]
Eu, como usuário do sistema, desejo cadastrar módulos de registro de medicamentos.

#### Cadastrar:
- [ ] Nome do módulo

https://github.com/zero101010/PI1_2018_2/wiki/UC05-Cadastrar-Módulos

**Comment by cantuariavc** [comment]
https://github.com/zero101010/PI1_2018_2/commit/28127c93b7a6f2bcf267628320615caecb637c5c
