### ISSUE TITLE
US07 - Editar Módulos

### ISSUE THREAD

**Issue by vinicinolivera** [zero101010/PI1_2018_2#21]
Eu, como usuário do sistema, desejo modificar dados de módulos já cadastrados.

https://github.com/zero101010/PI1_2018_2/wiki/UC07-Editar-Módulos

**Comment by cantuariavc** [comment]
https://github.com/zero101010/PI1_2018_2/commit/28127c93b7a6f2bcf267628320615caecb637c5c
