### ISSUE TITLE
US09 - Cadastrar Medicamento

### ISSUE THREAD

**Issue by vinicinolivera** [zero101010/PI1_2018_2#23]
Eu, como usuário do sistema, desejo cadastrar medicamento em seus respectivo módulos.

#### Cadastrar:
- [x] Nome
- [x] Horários
- [x] Nome da pessoa que deve tomar medicamento
- [x] Dosagem do medicamento

https://github.com/zero101010/PI1_2018_2/wiki/UC09-Cadastrar-Novo-Medicamento

**Comment by cantuariavc** [comment]
https://github.com/zero101010/PI1_2018_2/commit/2662245eb4ca73ed85b34d35a4faa7ca48db2ef9
