### ISSUE TITLE
US10 - Visualizar Medicamentos

### ISSUE THREAD

**Issue by vinicinolivera** [zero101010/PI1_2018_2#24]
Eu, como usuário do sistema, desejo verificar informações de medicamentos dos módulos.

https://github.com/zero101010/PI1_2018_2/wiki/UC10-Visualizar-Medicamentos

**Comment by cantuariavc** [comment]
https://github.com/zero101010/PI1_2018_2/commit/2662245eb4ca73ed85b34d35a4faa7ca48db2ef9
