### ISSUE TITLE
US11 - Editar Medicamentos

### ISSUE THREAD

**Issue by vinicinolivera** [zero101010/PI1_2018_2#25]
Eu, como usuário do sistema, desejo modificar dados de medicamentos já cadastrados nos módulos.

https://github.com/zero101010/PI1_2018_2/wiki/UC11-Editar-Medicamentos

**Comment by cantuariavc** [comment]
https://github.com/zero101010/PI1_2018_2/commit/2662245eb4ca73ed85b34d35a4faa7ca48db2ef9
